apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    helm.sh/chart: {{ include "grafana.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.admin.password }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.admin.password }}
  {{- else }}
  GF_SECURITY_ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
  {{- if and .Values.smtp.user .Values.smtp.password }}
  GF_SMTP_USER: {{ .Values.smtp.user }}
  GF_SMTP_PASSWORD: {{ .Values.smtp.password }}
  {{- end }}
  {{- end }}
