apiVersion: v1
name: grafana
version: 1.5.0
appVersion: 6.7.2
description: Grafana is an open source, feature rich metrics dashboard and graph editor for Graphite, Elasticsearch, OpenTSDB, Prometheus and InfluxDB.
keywords:
  - analitics
  - monitoring
  - metrics
  - logs
home: https://grafana.com/
sources:
  - https://github.com/bitnami/bitnami-docker-grafana
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/grafana/img/grafana-stack-220x234.png
